//ORGANIZATION
export const ORGANIZATION_START = 'ORGANIZATION_START';
export const ORGANIZATION_SUCCESS = 'ORGANIZATION_SUCCESS';
export const ORGANIZATION_GET_ALL = 'ORGANIZATION_GET_ALL';
export const ORGANIZATION_FINISH = 'ORGANIZATION_FINISH';
export const ORGANIZATION_FAIL = 'ORGANIZATION_FAIL';
export const ORGANIZATION_ADD = 'ORGANIZATION_ADD';